---
repos:
  -
    repo: 'git://github.com/pre-commit/pre-commit-hooks'
    rev: v2.1.0
    hooks:
      -
        id: trailing-whitespace
        stages:
          - commit
          - push
      -
        id: check-json
        stages:
          - commit
          - push
      -
        id: flake8
        stages:
          - commit
          - push
        exclude: ^bootstrap-buildout.py$
      -
        id: check-yaml
        stages:
          - commit
          - push
      -
        id: check-json
        stages:
          - commit
          - push
      -
        id: check-merge-conflict
        stages:
          - commit
          - push
      -
        id: debug-statements
        stages:
          - commit
          - push
      -
        id: fix-encoding-pragma
        stages:
          - commit
          - push
      -
        id: check-symlinks
        stages:
          - commit
          - push
      -
        id: debug-statements
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/jumanjihouse/pre-commit-hooks.git'
    rev: 1.11.0
    hooks:
      -
        id: shellcheck
        stages:
          - commit
          - push
      -
        id: shfmt
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/asottile/yesqa'
    rev: v0.0.10
    hooks:
      -
        id: yesqa
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.15.0
    hooks:
      -
        id: yamllint
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/jorisroovers/gitlint.git'
    rev: v0.11.0
    hooks:
      -
        id: gitlint
        stages:
          - commit-msg
  -
    repo: local
    hooks:
      -
        id: check-dockerfile
        name: 'Check dockerfile'
        entry: 'bash -c "docker run --rm -i hadolint/hadolint < Dockerfile"'
        pass_filenames: false
        language: system
        types:
          - dockerfile
        stages:
          - commit
          - push

  - repo: local
    hooks:
      - id: run-csslint
        name: Running CSS Lint
        entry: bin/code-analysis-csslint
        language: system
        stages: [commit, push]

  - repo: local
    hooks:
      - id: run-analysis-clean-lines
        name: Running analysis clean lines
        entry: bin/code-analysis-clean-lines
        language: system
        stages: [commit, push]

  - repo: local
    hooks:
      - id: run-code-analysis-find-untranslated
        name: Running analysis find untranslated
        entry: bin/code-analysis-find-untranslated
        language: system
        stages: [commit, push]

  - repo: local
    hooks:
      - id: run-code-analysis-jscs
        name: Running code analysis jscs
        entry: bin/code-analysis-jscs
        language: system
        stages: [commit, push]

  - repo: local
    hooks:
      - id: run-code-analysis-jshint
        name: Running code analysis jshint
        entry: bin/code-analysis-jshint
        language: system
        stages: [commit, push]

  - repo: local
    hooks:
      - id: run-code-analysis-zptlint
        name: Running code analysis zptlint
        entry: bin/code-analysis-zptlint
        language: system
        stages: [commit, push]
  - repo: local
    hooks:
      - id: run-tests
        name: Running unit tests
        entry: bin/test
        pass_filenames: false
        language: system
        stages: [commit, push]
  - repo: 'https://github.com/ambv/black.git'
    rev: 19.3b0
    hooks:
      - id: black
        name: black
        description: 'Black: The uncompromising Python code formatter'
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [python]
